name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, nightly, macos]
        include:
        - build: stable
          os: ubuntu-18.04
          rust: stable
        - build: nightly
          os: ubuntu-18.04
          rust: nightly
        - build: macos
          os: macOS-latest
          rust: stable
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build System Info
      run: rustc --version
    - name: Test
      run: cargo test
    - name: Build
      run: cargo build
